### ISSUE TITLE
Fatal Error in release:list and release:enable command

### ISSUE THREAD

**Issue by azurams** [octower/octower#55]
When execute the command `release:list` I have this fatal error

```
php octower.phar release:list preprod                                                                                                                           ?[master]
Connecting to cd33 (port: 22)
    Username to connect with? root
    Authentification mode:
        k - public key
        p - password
        ? - print help
    Your choice [k,p,?]? p
    Password to connect with?
Connected to the server
exec "ls -l | grep octower.phar" in /var/www/project
exec "php octower.phar server:info --automation --no-ansi" in /var/www/project
PHP Fatal error:  Uncaught Error: Call to a member function write() on null in phar:///Users/wblancditjolicoeur/testoctower/octower.phar/src/Octower/Remote/SshRemote.php:125
Stack trace:
#0 phar:///Users/wblancditjolicoeur/testoctower/octower.phar/src/Octower/Command/ReleaseListCommand.php(51): Octower\Remote\SshRemote->execServerCommand('server:release:...')
#1 phar:///Users/wblancditjolicoeur/testoctower/octower.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Octower\Command\ReleaseListCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///Users/wblancditjolicoeur/testoctower/octower.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///Users/wblancditjolicoeur/testoctower/octower.phar/vendor/symfony/console/Symfony/Component/Conso in phar:///Users/wblancditjolicoeur/testoctower/octower.phar/src/Octower/Remote/SshRemote.php on line 125
```

**Comment by borisschapira** [comment]
Did you try to SSH manually to the server in order to execute `php octopher.phar server:release:list` ?

**Comment by azurams** [comment]
The command `server:release:list` executed from server instance is ok , but command `release:list <remote>` executed from project instance fails the way i described.

If I understand, to get around this issue, I have to `php octower.phar deploy <remote> --generate` from project instance, then go on `<remote>` instance, and `php octower.phar server:release:list` and `php octower.phar server:release:enable <release_id>`.

One other thing that was not clear is the way "file-dist" generator works.
I figured out that if I configure a "shared" item this way : 
````
shared": {
        "app/config/settings.php": {
            "generator": "file-dist"
        },
````
I need to add a `app/config/settings.php.dist` in my project where I should replace some configuration values specifics to "<remote>" (bdd, base_url...) maybe using `sed` in `pre-enable` event command.

Am I correct ?

**Comment by borisschapira** [comment]
> If I understand, to get around this issue, I have to `php octower.phar deploy <remote> --generate` from project instance, then go on `<remote>` instance, and `php octower.phar server:release:list` and `php octower.phar server:release:enable <release_id>`.

I never used the deployment capabilities of Octower myself, as I am not open to the idea of opening server access to all developpers, so I build a package manualy, sftp-it to the server, and use `php octower.phar server:release:list`, `php octower.phar server:release:enable LATEST` and `php octower.phar server:release:clean` to keep my `releases` folder small and tidy.

**Comment by wpottier** [comment]
Ok it been fixed in the latest version (on develop branch)
